In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

In [11]:
n1=np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [12]:
n2=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,3]])
n2

<ipython-input-12-fda17e6f0e05>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  n2=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,3]])


array([list([1, 2, 3, 4, 5]), list([1, 2, 3, 4, 5]), list([1, 2, 3, 3])],
      dtype=object)

In [6]:
type(n2)

numpy.ndarray

In [7]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
n1=np.full((2,2),5)
n1

array([[5, 5],
       [5, 5]])

In [20]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
n1=np.arange(10,20,5)
n1

array([10, 15])

In [14]:
n3=np.random.randint(1,100,5)
n3

array([45, 90, 38, 84, 91])

In [25]:
n3=np.array([[1,2,3,4],[4,5,6,7]])
n3.shape

(2, 4)

In [29]:
n3.shape=(4,2)
n3.shape

(4, 2)

In [30]:
n3

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [16]:
n4=np.array([1,2,3,4])
n5=np.array([5,6,7,8])
np.vstack((n4,n5))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
n4=np.array([1,2,3,4])
n5=np.array([5,6,7,8])
np.hstack((n4,n5))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
n4=np.array([1,2,3,4])
n5=np.array([5,6,7,8])
np.column_stack((n4,n5))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [18]:
n6=np.array([10,20,30,40])
n7=np.array([50,20,70,80])
np.intersect1d(n6,n7)

array([20])

In [19]:
n6=np.array([10,20,30,40])
n7=np.array([50,20,70,80])
np.setdiff1d(n6,n7)

array([10, 30, 40])

In [46]:
n1=np.array([20,30,30,40])
n2=np.array([20,30,60,40])
np.intersect1d(n1,n2)

array([20, 30, 40])

In [48]:
n1=np.array([20,30,30,40])
n2=np.array([20,30,60,40])
np.setdiff1d(n2,n1)

array([60])

In [50]:
n1=np.array([20,30,30,40])
n2=np.array([20,30,60,40])
np.sum((n1,n2))

270

In [51]:
n1=np.array([20,30,30,40])
n1=n1+2

In [52]:
n1

array([22, 32, 32, 42])

In [53]:
n1=np.array([20,30,30,40])
n1=n1-2
n1

array([18, 28, 28, 38])

In [54]:
n1=np.array([20,30,30,40])
n1=n1*2
n1

array([40, 60, 60, 80])

In [58]:
n1=np.array([20,30,30,40])
n1=n1/2
n1

array([10., 15., 15., 20.])

In [59]:
n1=np.array([20,30,30,40])
n2=np.array([20,30,60,40])
np.sum([n1,n2],axis=0)

array([40, 60, 90, 80])

In [60]:
n1=np.array([20,30,30,40])
n2=np.array([20,30,60,40])
np.sum([n1,n2],axis=1)

array([120, 150])

In [61]:
n1=np.array([20,30,30,40])
np.mean(n1)

30.0

In [65]:
n1=np.array([20,10,30,40,50])
np.median(n1)

30.0

In [20]:
n1=np.array([6,8,10,12,14,16,18,20])
np.std(n1)

4.58257569495584

In [67]:
n1=np.array([20,10,30,40,50])
np.save("my_numpy",n1)

In [70]:
n2=np.load("my_numpy.npy")
n2

array([20, 10, 30, 40, 50])

In [71]:
b = np.ones((5,2)) # Create an array of all ones
b

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
e = np.random.random((2,2) )

In [74]:
e

array([[0.00786082, 0.03057939],
       [0.98274626, 0.7950535 ]])

In [22]:
f = np.random.randint(100, size = (4,4) )

In [28]:
f

array([[36, 41, 44, 58],
       [82, 12, 60, 51],
       [41, 87, 64, 86],
       [97,  0, 85, 13]])

In [29]:
f[1,:]

array([82, 12, 60, 51])

In [32]:
# Get 1 and 2 row
f[0,1:2:]

array([41])

In [31]:
f[:, -2]

array([44, 60, 64, 85])

In [81]:
f[:,0]

array([12, 86, 12, 84])

In [82]:
f[:,0:2]

array([[12, 63],
       [86, 85],
       [12, 10],
       [84, 83]])

In [33]:
f

array([[36, 41, 44, 58],
       [82, 12, 60, 51],
       [41, 87, 64, 86],
       [97,  0, 85, 13]])

In [34]:
## slicing an array 
## All 
b = f[:2, 1:3]

In [35]:
b

array([[41, 44],
       [12, 60]])

In [36]:
## Get specific elements
np.array([f[0,1], f[2,2]])

array([41, 64])

In [91]:
arr_1 = np.array([[1,2,4], [2,3,4], [1,2,10]],)
print (arr_1)
arr_1>=3

[[ 1  2  4]
 [ 2  3  4]
 [ 1  2 10]]


array([[False, False,  True],
       [False,  True,  True],
       [False, False,  True]])

In [92]:
arr_1[arr_1>=3]

array([ 4,  3,  4, 10])

In [93]:
arr_2 = np.array([range(0,10), range(10,20), range(20,30)])
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [94]:
arr_2[arr_2>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [95]:
arr_2.shape

(3, 10)

In [96]:
d=np.reshape(arr_2, (5,6))

In [97]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [98]:
arr_1

array([[ 1,  2,  4],
       [ 2,  3,  4],
       [ 1,  2, 10]])

In [99]:
arr_1[arr_1>=3]

array([ 4,  3,  4, 10])

In [100]:
arr_1[arr_1>=3]=10

In [101]:
arr_1

array([[ 1,  2, 10],
       [ 2, 10, 10],
       [ 1,  2, 10]])

In [102]:
x = np.random.randint( 100, size = (5,5) )
y = np.random.randint( 100, size = (5,5) )

In [103]:
x

array([[77, 22, 68, 18, 34],
       [ 8, 40, 85, 64, 67],
       [78,  9, 65, 60, 14],
       [73, 95, 19, 23, 36],
       [17, 10, 45, 74, 25]])

In [104]:
y

array([[54, 85, 71, 62, 81],
       [ 6,  7, 58, 79, 75],
       [21, 69, 73, 82, 14],
       [77, 89, 33, 56, 33],
       [15, 58, 69,  0, 52]])

In [105]:
x+y

array([[131, 107, 139,  80, 115],
       [ 14,  47, 143, 143, 142],
       [ 99,  78, 138, 142,  28],
       [150, 184,  52,  79,  69],
       [ 32,  68, 114,  74,  77]])

In [106]:
x-y

array([[ 23, -63,  -3, -44, -47],
       [  2,  33,  27, -15,  -8],
       [ 57, -60,  -8, -22,   0],
       [ -4,   6, -14, -33,   3],
       [  2, -48, -24,  74, -27]])

In [107]:
x*y

array([[4158, 1870, 4828, 1116, 2754],
       [  48,  280, 4930, 5056, 5025],
       [1638,  621, 4745, 4920,  196],
       [5621, 8455,  627, 1288, 1188],
       [ 255,  580, 3105,    0, 1300]])

In [108]:
x/y

C:\Users\kumar\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[1.42592593, 0.25882353, 0.95774648, 0.29032258, 0.41975309],
       [1.33333333, 5.71428571, 1.46551724, 0.81012658, 0.89333333],
       [3.71428571, 0.13043478, 0.89041096, 0.73170732, 1.        ],
       [0.94805195, 1.06741573, 0.57575758, 0.41071429, 1.09090909],
       [1.13333333, 0.17241379, 0.65217391,        inf, 0.48076923]])

In [109]:
# Matrix Transpose
x.T

array([[77,  8, 78, 73, 17],
       [22, 40,  9, 95, 10],
       [68, 85, 65, 19, 45],
       [18, 64, 60, 23, 74],
       [34, 67, 14, 36, 25]])

In [110]:
# Matrix Transpose
y.T

array([[54,  6, 21, 77, 15],
       [85,  7, 69, 89, 58],
       [71, 58, 73, 33, 69],
       [62, 79, 82, 56,  0],
       [81, 75, 14, 33, 52]])

In [111]:
from numpy import linalg
import numpy as np

# Solving a set of linear equations 
> x + 2y+3z = 5 <br>
> 3x + y +4z = 7 <br>
> 4x + 3y =10

In [114]:
a = np.array([[1,2,3], [3,1,4],[4,3,0]])
b = np.array([5,7,10])
x = np.linalg.solve(a, b)
x

array([1.51428571, 1.31428571, 0.28571429])

In [115]:
np.allclose(np.dot(a, x), b)

True

In [116]:
a = np.array([[1, 2], [3, 4]])
np.linalg.inv( a )

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Calculating an eigen value and vector for a matrix

In [117]:
m1 = np.diag((1, 2, 3))
m1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [118]:
eigval, eigvec = np.linalg.eig( m1 )

In [119]:
eigval

array([1., 2., 3.])

In [120]:
eigvec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [125]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))
print(demo_matrix)
demo_matrix[2,3]

[[13 35 74 48]
 [23 37 37 38]
 [73 39 93 39]]


39