In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import linear_model

In [21]:
df=pd.read_csv("p.csv")

In [22]:
df

area   bedrooms  age  price
0   2400         2   12  55000
1   2800         2   15  56000
2   3200         3   16  60000
3   3400         3   18  65000
4   3600         3   20  67000
5   4000         4   22  69000
6   4200         4   28  74000
7   4400         4   24  78000
8   4600         5   26  80000
9   4800         5   30  82000

In [23]:
import math

In [24]:
df1=math.floor(df.bedrooms.median())

In [25]:
df1

3

In [26]:
df2=df.bedrooms.fillna(df1)
df2

0    2
1    2
2    3
3    3
4    3
5    4
6    4
7    4
8    5
9    5
Name: bedrooms, dtype: int64

In [37]:
df=pd.read_csv("p.csv")
df

Area  bedrooms  age  price
0  2400         2   12  55000
1  2800         2   15  56000
2  3200         3   16  60000
3  3400         3   18  65000
4  3600         3   20  67000
5  4000         4   22  69000
6  4200         4   28  74000
7  4400         4   24  78000
8  4600         5   26  80000
9  4800         5   30  82000

In [38]:
mlr = linear_model.LinearRegression()

In [40]:
mlr.fit(df[["Area","bedrooms","age"]],df.price)

LinearRegression()

In [41]:
mlr.coef_

array([11.5214624 , 63.19059015, 73.37440807])

In [42]:
mlr.intercept_

23740.363562299528

In [43]:
mlr.predict([[3000,3,40]])

array([61429.29884414])

In [44]:
mlr.predict([[3200,4,60]])

array([65264.27007485])

In [45]:
11.5214624*3000+63.19059015*3+73.37440807*40+23740.363562299528

61429.29885554953